#!/bin/sh
# Command: hxo-run
# This runs the target executable and loads hxo_loader.so with the help of LD_PRELOAD

if [ "$#" -eq 0 ]; then
    echo "Usage: hxo-run <executable>"
    exit 1
fi

#check if already patched....
ldd "$1" | grep hxo_loader.so > /dev/null

if [ $? -eq 0 ]; then
    #already patched so run normally
    $@
    exit 1
fi
#in case not patched already execute the elf with the help of LD_PRELOAD
export LD_PRELOAD=hxo_loader.so
$@
